<h4>Platform:</h4>
<pre>
  {PLATFORM_NAME} {PLATFORM_URL} {PLATFORM_ADDRESS} {SUPPORT_EMAIL} {SUPPORT_PHONE}
</pre>

<h4>Marchent:</h4>
<pre>
  {SHOP_NAME} {SHOP_URL} {SHOP_SUPPORT_EMAIL} {SHOP_SUPPORT_PHONE}
</pre>

<h4>Pages:</h4>
<pre>
  {CONTACT_US} {ABOUT_US} {PRIVACY_POLICY} {RETURN_AND_REFUND} {TERMS_AND_CONDITIONS_FOR_CUSTOMER} {TERMS_AND_CONDITIONS_FOR_MERCHANT}
</pre>